name: CD

on:
  create:
    tags:
      - v*

jobs:
  deploy:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set up Python [3.7]
      uses: actions/setup-python@v2
      with:
        python-version: 3.7

#    - name: Install dependencies
#      run: pip install -r requirements.txt

#    - name: Set env
#      run: echo ::set-env name=RELEASE_VERSION::${GITHUB_REF#refs/*/}
#
#    - name: Test variables
#      run: |
#        echo $RELEASE_VERSION
#        echo ${{ env.RELEASE_VERSION }}

    - name: Set up Cloud SDK
      uses: google-github-actions/setup-gcloud@master
      with:
        project_id: ${{ secrets.GCP_PROJECT_ID }}
        service_account_key: ${{ secrets.GCP_SA_KEY }}
        export_default_credentials: true

    - name: Copy app service account
      run: gsutil cp gs://crousorama-credentials/back/service-account.json ./src/config/credentials/service-account.json

    - name: Deploy
      run: gcloud app deploy api.yml --quiet --project=${{ secrets.GCP_PROJECT_ID }}